version: "1.0"
projectName: SIQA_GIT_0826Project
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: TimeoutTest
    type: workflow
    uid: fl974da43f6b97671a4afa23
    stepId: a0
    reference: SIQA_TimeoutTest:delayfor2Sec
- runtimeAlias: SIQA_ERT_0804
  assets:
  - name: Call_deepclonetest
    type: workflow
    uid: fl978b9b63b3f65322bf6d93
    stepId: a0
    reference: project.siqa_git_0826.integrations:deepclonetest
  - name: fld_1181857214_stage00.projects.fl4466c3e02ec5a212521db8.integrations:conntest
    type: flow
    stepId: /0
    reference: fld_1181857214_stage00.projects.fl4466c3e02ec5a212521db8.WmPackageServiceProvider.GB_1:readGlobalvariable
  - name: fld_1181857214_stage00.projects.fl4466c3e02ec5a212521db8.integrations:conntest
    type: flow
    stepId: /2
    reference: fld_1181857214_stage00.projects.fl4466c3e02ec5a212521db8.WmPackageServiceProvider.SIQAJDBCAdapterTests.adapterServices:getData
  - name: fld_1181857214_stage00.projects.fl4466c3e02ec5a212521db8.integrations:conntest
    type: flow
    stepId: /1
    reference: fld_1181857214_stage00.projects.fl4466c3e02ec5a212521db8.WmPackageServiceProvider.SIQACloudStreamsTests:connetorOperations
